OnlineShopProject/Controllers/CountriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineShopProject.Models;
using OnlineShopProject.Filters;

namespace OnlineShopProject
{
    public class CountriesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Countries
        public ActionResult Index()
        {
            return View(db.CountryModels.ToList());
        }

        [RejectUnauthorizedUsers]
        public ActionResult AdminIndex(string SearchPattern)
        {
            if (SearchPattern != null)
            {
                var countries = db.CountryModels.Where(x => x.Country.Contains(SearchPattern));
                ViewBag.SearchPattern = SearchPattern;
                return View(countries.ToList());
            }

            return View(db.CountryModels.ToList());
        }

        // GET: Countries/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CountryModel countryModel = db.CountryModels.Find(id);
            if (countryModel == null)
            {
                return HttpNotFound();
            }
            return View(countryModel);
        }

        // GET: Countries/Create
        [RejectUnauthorizedUsers]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Countries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [RejectUnauthorizedUsers]
        public ActionResult Create([Bind(Include = "Id,Country")] CountryModel countryModel)
        {
            if (ModelState.IsValid)
            {
                db.CountryModels.Add(countryModel);
                db.SaveChanges();
                return RedirectToAction("AdminIndex");
            }

            return View(countryModel);
        }

        // GET: Countries/Edit/5
        [RejectUnauthorizedUsers]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CountryModel countryModel = db.CountryModels.Find(id);
            if (countryModel == null)
            {
                return HttpNotFound();
            }
            return View(countryModel);
        }

        // POST: Countries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [RejectUnauthorizedUsers]
        public ActionResult Edit([Bind(Include = "Id,Country")] CountryModel countryModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(countryModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("AdminIndex");
            }
            return View(countryModel);
        }

        // GET: Countries/Delete/5
        [RejectUnauthorizedUsers]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CountryModel countryModel = db.CountryModels.Find(id);
            if (countryModel == null)
            {
                return HttpNotFound();
            }
            return View(countryModel);
        }

        // POST: Countries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [RejectUnauthorizedUsers]
        public ActionResult DeleteConfirmed(int id)
        {
            CountryModel countryModel = db.CountryModels.Find(id);
            db.CountryModels.Remove(countryModel);
            db.SaveChanges();
            return RedirectToAction("AdminIndex");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OnlineShopProject/Views/Countries/AdminIndex.cshtml
@model IEnumerable<OnlineShopProject.Models.CountryModel>

@{
    ViewBag.Title = "Index";
}

<section>
    <div class="container">
        <div class="row">
            <h2 class="title text-center admin-title">Edit Countries Items</h2>
            @using (Html.BeginForm("AdminIndex", "Countries", FormMethod.Get))
            {
                <div class="search_box">
                    <input type="text" placeholder="Search" name="SearchPattern" value="@ViewBag.SearchPattern" autofocus>
                </div>
                <input type="submit" value="Submit" class="hidden" />
            }
            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Country)
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Country)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>
</section>

OnlineShopProject/Views/Countries/Create.cshtml
@model OnlineShopProject.Models.CountryModel

@{
    ViewBag.Title = "Create";
}

<section>
    <div class="container">
        <h2 class="title text-center admin-title">Create Country</h2>
        <div class="row">
            <div class="col-sm-12">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Create" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</section>

OnlineShopProject/Views/Countries/Delete.cshtml
@model OnlineShopProject.Models.CountryModel

@{
    ViewBag.Title = "Delete";
}

<section>
    <div class="container">
        <h2 class="title text-center admin-title">Delete Country</h2>
        <div class="row">
            <div class="col-sm-12">
                <h3>Are you sure you want to delete this?</h3>
                <div>
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-actions no-color">
                            <a href="@Url.Action("AdminIndex", "Countries")" class="btn btn-default">Back to List</a>
                            <input type="submit" value="Delete" class="btn btn-danger" />
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>

OnlineShopProject/Views/Countries/Details.cshtml
@model OnlineShopProject.Models.CountryModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>CountryModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

OnlineShopProject/Views/Countries/Edit.cshtml
@model OnlineShopProject.Models.CountryModel

@{
    ViewBag.Title = "Edit";
}

<section>
    <div class="container">
        <h2 class="title text-center admin-title">Edit Country</h2>
        <div class="row">
            <div class="col-sm-12">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.Id)

                        <div class="form-group">
                            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Save" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</section>

OnlineShopProject/Views/Countries/Index.cshtml
@model IEnumerable<OnlineShopProject.Models.CountryModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Country)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Country)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>