OnlineShopProject/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineShopProject.Models;
using Microsoft.AspNet.Identity;

namespace OnlineShopProject.Controllers
{
    public class CartsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Carts
        public ActionResult Index()
        {
            ApplicationUser currentUser = db.Users.Find(User.Identity.GetUserId());
            ViewBag.user = GetCurrentUser();
            return View(db.CartModels.Where(x => x.Id == currentUser.CartModelId).Include(x => x.CartItems.Select(a => a.Album).Select(z => z.Artist)).SingleOrDefault());
        }

        private ApplicationUser GetCurrentUser()
        {
            if (Request.IsAuthenticated)
            {
                string currentUserId = User.Identity.GetUserId();
                ApplicationUser currentUser =
                    db.Users.Where(x => x.Id == currentUserId).Include(x => x.CurrencyModel).SingleOrDefault();
                return currentUser;
            }

            return null;
        }

        public ActionResult UpdateQuantity(int cartItemId, int changeVector)
        {
            CartItemModel cartItemModel = db.CartItemModels.Find(cartItemId);

            if (!((cartItemModel.Quantity + changeVector) < 0))
            {
                int newQuantity = cartItemModel.Quantity + changeVector;
                if (newQuantity <= 0)
                {
                    db.CartItemModels.Remove(cartItemModel);
                }
                else
                {
                    cartItemModel.Quantity = cartItemModel.Quantity + changeVector;
                }

                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        public ActionResult UpdateQuantityValue(int cartItemId, int newQuantity)
        {
            if (newQuantity > 0)
            {
                CartItemModel cartItemModel = db.CartItemModels.Find(cartItemId);
                cartItemModel.Quantity = newQuantity;
                db.SaveChanges();

                return new HttpStatusCodeResult(HttpStatusCode.OK);
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
        }

        // GET: Carts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CartModel cartModel = db.CartModels.Find(id);
            if (cartModel == null)
            {
                return HttpNotFound();
            }
            return View(cartModel);
        }

        // GET: Carts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Carts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id")] CartModel cartModel)
        {
            if (ModelState.IsValid)
            {
                db.CartModels.Add(cartModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cartModel);
        }

        // GET: Carts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CartModel cartModel = db.CartModels.Find(id);
            if (cartModel == null)
            {
                return HttpNotFound();
            }
            return View(cartModel);
        }

        // POST: Carts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id")] CartModel cartModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cartModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cartModel);
        }

        // GET: Carts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CartModel cartModel = db.CartModels.Find(id);
            if (cartModel == null)
            {
                return HttpNotFound();
            }
            return View(cartModel);
        }

        // POST: Carts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CartModel cartModel = db.CartModels.Find(id);
            db.CartModels.Remove(cartModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OnlineShopProject/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineShopProject.Models;
using Microsoft.AspNet.Identity;

namespace OnlineShopProject.Controllers
{
    public class OrdersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Orders
        public ActionResult Index()
        {
            string userId = User.Identity.GetUserId();

            var orderModels = db.OrderModels.Include(x => x.ApplicationUser).
                Where(x => x.ApplicationUser.Id == userId).
                OrderByDescending(x => x.CreatedAt).
                Include(o => o.BillingDetails).
                Include(x => x.OrderItems.
                    Select(a => a.Album).
                    Select(z => z.Artist));
            
            ViewBag.user = GetCurrentUser();

            return View(orderModels.ToList());
        }
        private ApplicationUser GetCurrentUser()
        {
            if (Request.IsAuthenticated)
            {
                string currentUserId = User.Identity.GetUserId();
                ApplicationUser currentUser =
                    db.Users.Where(x => x.Id == currentUserId).Include(x => x.CurrencyModel).SingleOrDefault();
                return currentUser;
            }

            return null;
        }

        // GET: Orders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderModel orderModel = db.OrderModels.Find(id);
            if (orderModel == null)
            {
                return HttpNotFound();
            }
            return View(orderModel);
        }

        // GET: Orders/Create
        public ActionResult Create()
        {
            if (Request.IsAuthenticated)
            {
                ApplicationUser currentUser = db.Users.Find(User.Identity.GetUserId());
                CartModel cartModel = db.CartModels.Where(x => x.Id == currentUser.CartModelId).Include(x => x.CartItems.Select(a => a.Album).Select(z => z.Artist)).SingleOrDefault();

                ViewBag.CartModel = cartModel;
                ViewBag.CountryId = new SelectList(db.CountryModels, "Id", "Country");
                ViewBag.BillingDetailsId = new SelectList(db.BillingDetailsModels, "Id", "FirstName");

                ViewBag.user = GetCurrentUser();

                return View();
            }

            return RedirectToAction("Index", "Albums");
        }

        // POST: Orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FirstName,LastName,Address,City,ZipCode,CountryId,Phone,CreditCardNumber,ExpirationMonth,ExpirationYear,CVV2")] BillingDetailsModel billingDetailsModel, int CartModelId)
        {
            ApplicationUser currentUser = db.Users.Find(User.Identity.GetUserId());

            if (ModelState.IsValid)
            {
                db.BillingDetailsModels.Add(billingDetailsModel);

                OrderModel orderModel = new OrderModel()
                {
                    BillingDetailsId = billingDetailsModel.Id,
                    ApplicationUser = currentUser,
                    CreatedAt = DateTime.Now
                };

                db.OrderModels.Add(orderModel);

                CartModel cartModel = db.CartModels.Where(x => x.Id == CartModelId).Include(x => x.CartItems.Select(a => a.Album)).SingleOrDefault();

                foreach (CartItemModel item in cartModel.CartItems)
                {
                    db.OrderItemModels.Add(new OrderItemModel()
                    {
                        AlbumId = item.AlbumId,
                        OrderModelId = orderModel.Id,
                        Price = item.Album.Price,
                        Quantity = item.Quantity
                    });
                }

                db.CartItemModels.RemoveRange(cartModel.CartItems);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            CartModel userCartModel = db.CartModels.Where(x => x.Id == currentUser.CartModelId).Include(x => x.CartItems.Select(a => a.Album).Select(z => z.Artist)).SingleOrDefault();

            ViewBag.CartModel = userCartModel;
            ViewBag.CountryId = new SelectList(db.CountryModels, "Id", "Country");
            ViewBag.BillingDetailsId = new SelectList(db.BillingDetailsModels, "Id", "FirstName");

            ViewBag.user = GetCurrentUser();

            return View();

        }

        // GET: Orders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderModel orderModel = db.OrderModels.Find(id);
            if (orderModel == null)
            {
                return HttpNotFound();
            }
            ViewBag.BillingDetailsId = new SelectList(db.BillingDetailsModels, "Id", "FirstName", orderModel.BillingDetailsId);
            return View(orderModel);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,BillingDetailsId")] OrderModel orderModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(orderModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BillingDetailsId = new SelectList(db.BillingDetailsModels, "Id", "FirstName", orderModel.BillingDetailsId);
            return View(orderModel);
        }

        // GET: Orders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderModel orderModel = db.OrderModels.Find(id);
            if (orderModel == null)
            {
                return HttpNotFound();
            }
            return View(orderModel);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            OrderModel orderModel = db.OrderModels.Find(id);
            db.OrderModels.Remove(orderModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OnlineShopProject/Views/Orders/Create.cshtml
@model OnlineShopProject.Models.OrderModel

@{
    ViewBag.Title = "Create";
}

<section id="cart_items">
    <div class="container">
        <div class="breadcrumbs">
            <ol class="breadcrumb">
                <li><a href="@Url.Action("Index", "Albums")">Home</a></li>
                <li class="active">Checkout</li>
            </ol>
        </div><!--/breadcrums-->
        <form action="@Url.Action("Create", "Orders")" method="post">
            @Html.AntiForgeryToken()
            @Html.Hidden("CartModelId", (int)ViewBag.CartModel.Id)
            <div class="shopper-informations">
                <div class="row">
                    <div class="col-sm-5 clearfix">
                        <div class="bill-to">
                            <p>Billing Details</p>
                            <div class="form-one">
                                @Html.ValidationMessage("FirstName", "", new { @class = "text-danger" })
                                <input type="text" placeholder="First Name" name="FirstName">
                                @Html.ValidationMessage("LastName", "", new { @class = "text-danger" })
                                <input type="text" placeholder="Last Name" name="LastName">
                                @Html.ValidationMessage("Address", "", new { @class = "text-danger" })
                                <input type="text" placeholder="Address" name="Address">
                                @Html.ValidationMessage("City", "", new { @class = "text-danger" })
                                <input type="text" placeholder="City" name="City">
                                @Html.ValidationMessage("ZipCode", "", new { @class = "text-danger" })
                                <input type="text" placeholder="Zip Code" name="ZipCode">
                                @Html.ValidationMessage("CountryId", "", new { @class = "text-danger" })
                                @Html.DropDownList("CountryId")
                                @Html.ValidationMessage("Phone", "", new { @class = "text-danger" })
                                <input type="text" placeholder="Phone" name="Phone">
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-5 clearfix">
                        <div class="bill-to">
                            <p>Payment Details</p>
                            <div class="form-one">
                                @Html.ValidationMessage("CreditCardNumber", "", new { @class = "text-danger" })
                                <input type="text" placeholder="Credit Card Number" name="CreditCardNumber">
                                @Html.ValidationMessage("ExpirationMonth", "", new { @class = "text-danger" })
                                <input type="number" min="1" max="12" placeholder="Expiration Month" name="ExpirationMonth">
                                @Html.ValidationMessage("ExpirationYear", "", new { @class = "text-danger" })
                                <input type="number" min="2015" max="2030" placeholder="Expiration Year" name="ExpirationYear">
                                @Html.ValidationMessage("CVV2", "", new { @class = "text-danger" })
                                <input type="text" placeholder="CVV2" name="CVV2">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="review-payment">
                <h2>Review &amp; Payment</h2>
            </div>

            <div class="table-responsive cart_info">
                <table class="table table-condensed orders-cart-summary">
                    <thead>
                        <tr class="cart_menu">
                            <td class="image">Item</td>
                            <td class="description"></td>
                            <td class="price">Price</td>
                            <td class="quantity">Quantity</td>
                            <td class="total">Total</td>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            double totalPrice = 0;
                        }
                        @foreach (var item in ViewBag.CartModel.CartItems)
                        {
                            <tr>
                                <td class="cart_product">
                                    <a href=""><img src="@item.Album.ImagePath" alt="" class="cart-product-image"></a>
                                </td>
                                <td class="cart_description">
                                    <h4><a href="">@item.Album.Name</a></h4>
                                    <p>By @item.Album.Artist.Name</p>
                                </td>
                                <td class="cart_price">
                                    <p>@Helpers.GetCurrencyAndPrice(ViewBag.user, item.Album.Price)</p>
                                </td>
                                <td class="cart_quantity" data-cart-item-id="@item.Id">
                                    <label class="quantity-label">@item.Quantity</label>
                                </td>
                                <td class="cart_total">
                                    <p class="cart_total_price">@Helpers.GetCurrencyAndPrice(ViewBag.user, item.Album.Price * item.Quantity)</p>
                                    @{
                            totalPrice += item.Album.Price * item.Quantity;
                                    }
                                </td>
                            </tr>
                        }
                        <tr>
                            <td colspan="4">&nbsp;</td>
                            <td colspan="2">
                                <table class="table table-condensed total-result">
                                    <tbody>
                                        <tr>
                                            <td>Cart Sub Total</td>
                                            <td>@Helpers.GetCurrencyAndPrice(ViewBag.user, totalPrice)</td>
                                        </tr>
                                        <tr class="shipping-cost">
                                            <td>Shipping Cost</td>
                                            <td>Free</td>
                                        </tr>
                                        <tr>
                                            <td>Total</td>
                                            <td><span>@Helpers.GetCurrencyAndPrice(ViewBag.user, totalPrice)</span></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <a class="btn btn-default check_out return_to_cart" href="@Url.Action("Index", "Carts")">Edit Order</a>
            <button type="submit" class="btn btn-default check_out place_order">Place Order</button>
        </form>
    </div>
</section>

OnlineShopProject/Views/Orders/Delete.cshtml
@model OnlineShopProject.Models.OrderModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>OrderModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BillingDetails.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BillingDetails.FirstName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

OnlineShopProject/Views/Orders/Details.cshtml
@model OnlineShopProject.Models.OrderModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>OrderModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BillingDetails.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BillingDetails.FirstName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

OnlineShopProject/Views/Orders/Edit.cshtml
@model OnlineShopProject.Models.OrderModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>OrderModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.BillingDetailsId, "BillingDetailsId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BillingDetailsId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BillingDetailsId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

OnlineShopProject/Views/Orders/Index.cshtml
@model IEnumerable<OnlineShopProject.Models.OrderModel>
<!-- TODO: CHECK IN ALL LIKE THIS THAT THIS ARRAY IS ONLY FOR THE CURRENT USER -->

@{
    ViewBag.Title = "Index";
}

<section id="cart_items">
    <div class="container">
        <div class="breadcrumbs">
            <ol class="breadcrumb">
                <li><a href="@Url.Action("Index", "Albums")">Home</a></li>
                <li class="active">Orders History</li>
            </ol>
        </div><!--/breadcrums-->
        @{ int orderIndex = Model.Count(); }

        @if (orderIndex <= 0)
        {
            <h2 class="text-center even-margin">No orders found.</h2>   
        }

        @foreach (var orderModel in Model)
        {
            <div class="review-payment">
                <h2>Order #@orderIndex - @orderModel.CreatedAt.ToShortDateString() @orderModel.CreatedAt.ToShortTimeString()</h2>
                @{ orderIndex--; }
            </div>
            <div class="table-responsive cart_info history-cart">
                    <table class="table table-condensed orders-cart-summary">
                        <thead>
                            <tr class="cart_menu">
                                <td class="image">Item</td>
                                <td class="description"></td>
                                <td class="price">Price</td>
                                <td class="quantity">Quantity</td>
                                <td class="total">Total</td>
                            </tr>
                        </thead>
                        <tbody>
                            @{ double totalPrice = 0; }
                            @foreach (var item in orderModel.OrderItems)
                            {
                                <tr>
                                    <td class="cart_product">
                                        <a href="@Url.Action("Details", "Albums", new { Id = item.AlbumId })"><img src="@item.Album.ImagePath" alt="" class="cart-product-image"></a>
                                    </td>
                                    <td class="cart_description">
                                        <h4><a href="@Url.Action("Details", "Albums", new { Id = item.AlbumId })">@item.Album.Name</a></h4>
                                        <p>By @item.Album.Artist.Name</p>
                                    </td>
                                    <td class="cart_price">
                                        <p>@Helpers.GetCurrencyAndPrice(ViewBag.user, item.Album.Price)</p>
                                    </td>
                                    <td class="cart_quantity" data-cart-item-id="@item.Id">
                                        <label class="quantity-label">@item.Quantity</label>
                                    </td>
                                    <td class="cart_total">
                                        <p class="cart_total_price">@Helpers.GetCurrencyAndPrice(ViewBag.user, item.Album.Price * item.Quantity)</p>
                                        @{
                                totalPrice += item.Album.Price * item.Quantity;
                                        }
                                    </td>
                                </tr>
                            }
                            <tr>
                                <td colspan="4">&nbsp;</td>
                                <td colspan="2">
                                    <table class="table table-condensed total-result">
                                        <tbody>
                                            <tr>
                                                <td>Cart Sub Total</td>
                                                <td>@Helpers.GetCurrencyAndPrice(ViewBag.user, totalPrice)</td>
                                            </tr>
                                            <tr class="shipping-cost">
                                                <td>Shipping Cost</td>
                                                <td>Free</td>
                                            </tr>
                                            <tr>
                                                <td>Total</td>
                                                <td><span>@Helpers.GetCurrencyAndPrice(ViewBag.user, totalPrice)</span></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                        </tbody>
                    </table>   
            </div>
        }
    </div>
</section>