OnlineShopProject/Controllers/AlbumsController.cs
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using System.IO;
using System.Web.Routing;
using OnlineShopProject.Controllers;
using OnlineShopProject.Filters;
using PagedList;

namespace OnlineShopProject.Models
{
    public class AlbumsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Albums
        public ActionResult Index(int page = 1, int pageSize = 6)
        {
            var albumModels = db.AlbumModels.Include(a => a.Artist).Include(a => a.Genre).OrderByDescending(x => x.ReleaseDate);

            SetCarModelId();

            ViewBag.user = GetCurrentUser();

            ViewBag.ActionName = "Index";

            return View(albumModels.ToPagedList(page, pageSize));
        }

        private ApplicationUser GetCurrentUser()
        {
            if (Request.IsAuthenticated)
            {
                string currentUserId = User.Identity.GetUserId();
                ApplicationUser currentUser =
                    db.Users.Where(x => x.Id == currentUserId).Include(x => x.CurrencyModel).SingleOrDefault();
                return currentUser;
            }

            return null;
        }

        [RejectUnauthorizedUsers]
        public ActionResult AdminIndex(string SearchPattern)
        {
            var albumModels = db.AlbumModels.Include(a => a.Artist).Include(a => a.Genre);

            if (SearchPattern != null)
            {
                albumModels = albumModels.Where(x => x.Name.Contains(SearchPattern) || x.Genre.Name.Contains(SearchPattern) || x.Artist.Name.Contains(SearchPattern));
                ViewBag.SearchPattern = SearchPattern;
            }

            return View(albumModels.ToList());
        }

        public ActionResult Filter(int? genre, int? artist, int? decade, double? price, int page = 1, int pageSize = 6)
        {
            IQueryable<AlbumModel> filterQuery = db.AlbumModels;

            if (decade != null)
            {
                int intDecate = (int)decade;
                ViewBag.decade = intDecate;
                DateTime bottomDateTime = new DateTime(intDecate, 1, 1);
                DateTime higherDateTime = new DateTime(intDecate + 10, 1, 1);

                filterQuery = filterQuery.Where(a => a.ReleaseDate >= bottomDateTime &&
                                                        a.ReleaseDate < higherDateTime);
            }

            if (genre != null)
            {
                int inGenreId = (int)genre;
                ViewBag.genre = inGenreId;
                filterQuery = filterQuery.Where(g => g.GenreId == inGenreId);
            }

            if (artist != null)
            {
                int intArtistId = (int)artist;
                ViewBag.artist = intArtistId;
                filterQuery = filterQuery.Where(a => a.ArtistId == intArtistId);
            }

            if (price != null)
            {
                double doublePrice = (double)price;
                ViewBag.price = doublePrice;

                if (price == 20)
                {
                    filterQuery = filterQuery.Where(p => p.Price >= doublePrice);
                }
                else
                {
                    filterQuery = filterQuery.Where(p => p.Price >= doublePrice && p.Price <= doublePrice + 5);
                }
            }

            SetCarModelId();
            ViewBag.user = GetCurrentUser();
            ViewBag.ActionName = "Filter";

            return View(filterQuery.OrderByDescending(x => x.ReleaseDate).ToPagedList(page, pageSize));
        }


        // GET: Albums/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            AlbumModel albumModel = db.AlbumModels.Where(x => x.Id == id).
                Include(x => x.Genre).
                Include(x => x.Songs).
                Include(x => x.Artist).
                Include(x => x.Reviews.Select(u => u.ApplicationUser)).SingleOrDefault();

            SetCarModelId();
            ViewBag.user = GetCurrentUser();

            if (albumModel == null)
            {
                return HttpNotFound();
            }
            return View(albumModel);
        }

        // GET: Albums/Create
        [RejectUnauthorizedUsers]
        public ActionResult Create()
        {
            ViewBag.ArtistId = new SelectList(db.ArtistModels, "Id", "Name");
            ViewBag.GenreId = new SelectList(db.GenreModels, "Id", "Name");
            return View();
        }

        // POST: Albums/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [RejectUnauthorizedUsers]
        public ActionResult Create([Bind(Include = "Id,ArtistId,ReleaseDate,GenreId,Name,Price")] AlbumModel albumModel, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                if (image != null && image.ContentLength > 0)
                {
                    string path = Server.MapPath("~//Uploads/Albums/CD_Covers");
                    string fullPath = Path.Combine(path, image.FileName);
                    image.SaveAs(fullPath);
                    albumModel.ImagePath = "/Uploads/Albums/CD_Covers/" + image.FileName;
                }

                db.AlbumModels.Add(albumModel);
                db.SaveChanges();
                return RedirectToAction("AdminIndex");
            }

            ViewBag.ArtistId = new SelectList(db.ArtistModels, "Id", "Name", albumModel.ArtistId);
            ViewBag.GenreId = new SelectList(db.GenreModels, "Id", "Name", albumModel.GenreId);
            return View(albumModel);
        }

        // GET: Albums/Edit/5
        [RejectUnauthorizedUsers]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AlbumModel albumModel = db.AlbumModels.Find(id);
            if (albumModel == null)
            {
                return HttpNotFound();
            }

            ViewBag.ArtistId = new SelectList(db.ArtistModels, "Id", "Name", albumModel.ArtistId);
            ViewBag.GenreId = new SelectList(db.GenreModels, "Id", "Name", albumModel.GenreId);
            return View(albumModel);
        }

        // POST: Albums/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [RejectUnauthorizedUsers]
        public ActionResult Edit([Bind(Include = "Id,ArtistId,ReleaseDate,GenreId,Name,Price,ImagePath")] AlbumModel albumModel, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                db.Entry(albumModel).State = EntityState.Modified;

                if (image != null && image.ContentLength > 0)
                {
                    string path = Server.MapPath("~//Uploads/Albums/CD_Covers");
                    string fullPath = Path.Combine(path, image.FileName);
                    image.SaveAs(fullPath);
                    albumModel.ImagePath = "/Uploads/Albums/CD_Covers/" + image.FileName;
                }

                db.SaveChanges();
                return RedirectToAction("AdminIndex");
            }

            ViewBag.ArtistId = new SelectList(db.ArtistModels, "Id", "Name", albumModel.ArtistId);
            ViewBag.GenreId = new SelectList(db.GenreModels, "Id", "Name", albumModel.GenreId);
            return View(albumModel);
        }

        // GET: Albums/Delete/5
        [RejectUnauthorizedUsers]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AlbumModel albumModel = db.AlbumModels.Find(id);
            if (albumModel == null)
            {
                return HttpNotFound();
            }
            return View(albumModel);
        }

        // POST: Albums/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [RejectUnauthorizedUsers]
        public ActionResult DeleteConfirmed(int id)
        {
            AlbumModel albumModel = db.AlbumModels.Find(id);
            db.AlbumModels.Remove(albumModel);
            db.SaveChanges();
            return RedirectToAction("AdminIndex");
        }

        private void SetCarModelId()
        {
            if (Request.IsAuthenticated)
            {
                ApplicationUser currentUser = db.Users.Find(User.Identity.GetUserId());
                ViewBag.CartModelId = currentUser.CartModelId;
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OnlineShopProject/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineShopProject.Models;
using Microsoft.AspNet.Identity;

namespace OnlineShopProject.Controllers
{
    public class CartsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Carts
        public ActionResult Index()
        {
            ApplicationUser currentUser = db.Users.Find(User.Identity.GetUserId());
            ViewBag.user = GetCurrentUser();
            return View(db.CartModels.Where(x => x.Id == currentUser.CartModelId).Include(x => x.CartItems.Select(a => a.Album).Select(z => z.Artist)).SingleOrDefault());
        }

        private ApplicationUser GetCurrentUser()
        {
            if (Request.IsAuthenticated)
            {
                string currentUserId = User.Identity.GetUserId();
                ApplicationUser currentUser =
                    db.Users.Where(x => x.Id == currentUserId).Include(x => x.CurrencyModel).SingleOrDefault();
                return currentUser;
            }

            return null;
        }

        public ActionResult UpdateQuantity(int cartItemId, int changeVector)
        {
            CartItemModel cartItemModel = db.CartItemModels.Find(cartItemId);

            if (!((cartItemModel.Quantity + changeVector) < 0))
            {
                int newQuantity = cartItemModel.Quantity + changeVector;
                if (newQuantity <= 0)
                {
                    db.CartItemModels.Remove(cartItemModel);
                }
                else
                {
                    cartItemModel.Quantity = cartItemModel.Quantity + changeVector;
                }

                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        public ActionResult UpdateQuantityValue(int cartItemId, int newQuantity)
        {
            if (newQuantity > 0)
            {
                CartItemModel cartItemModel = db.CartItemModels.Find(cartItemId);
                cartItemModel.Quantity = newQuantity;
                db.SaveChanges();

                return new HttpStatusCodeResult(HttpStatusCode.OK);
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
        }

        // GET: Carts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CartModel cartModel = db.CartModels.Find(id);
            if (cartModel == null)
            {
                return HttpNotFound();
            }
            return View(cartModel);
        }

        // GET: Carts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Carts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id")] CartModel cartModel)
        {
            if (ModelState.IsValid)
            {
                db.CartModels.Add(cartModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cartModel);
        }

        // GET: Carts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CartModel cartModel = db.CartModels.Find(id);
            if (cartModel == null)
            {
                return HttpNotFound();
            }
            return View(cartModel);
        }

        // POST: Carts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id")] CartModel cartModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cartModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cartModel);
        }

        // GET: Carts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CartModel cartModel = db.CartModels.Find(id);
            if (cartModel == null)
            {
                return HttpNotFound();
            }
            return View(cartModel);
        }

        // POST: Carts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CartModel cartModel = db.CartModels.Find(id);
            db.CartModels.Remove(cartModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OnlineShopProject/Views/Carts/Create.cshtml
@model OnlineShopProject.Models.CartModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CartModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

OnlineShopProject/Views/Carts/Delete.cshtml
@model OnlineShopProject.Models.CartModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CartModel</h4>
    <hr />
    <dl class="dl-horizontal">
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

OnlineShopProject/Views/Carts/Details.cshtml
@model OnlineShopProject.Models.CartModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>CartModel</h4>
    <hr />
    <dl class="dl-horizontal">
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

OnlineShopProject/Views/Carts/Edit.cshtml
@model OnlineShopProject.Models.CartModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CartModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

OnlineShopProject/Views/Carts/Index.cshtml
@model OnlineShopProject.Models.CartModel

@{
    ViewBag.Title = "Index";
}
<section id="cart_items">
    <div class="container">
        @* TODO: COOL MENU - USE IN SITE! *@
        <div class="breadcrumbs">
            <ol class="breadcrumb">
                <li><a href="@Url.Action("Index", "Albums")">Home</a></li>
                <li class="active">Shopping Cart</li>
            </ol>
        </div>
        <div class="table-responsive cart_info">
            @if (Model.CartItems.Count == 0)
            {
                <h2 class="text-center even-margin">No items in cart.</h2>   
            }
            else
            {
                <table class="table table-condensed">
                    <thead>
                        <tr class="cart_menu">
                            <td class="image">Item</td>
                            <td class="description"></td>
                            <td class="price">Price</td>
                            <td class="quantity">Quantity</td>
                            <td class="total">Total</td>
                            <td></td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.CartItems)
                        {
                            <tr>
                                <td class="cart_product">
                                    <a href="@Url.Action("Details", "Albums", new { Id = item.AlbumId })"><img src="@item.Album.ImagePath" alt="" class="cart-product-image"></a>
                                </td>
                                <td class="cart_description">
                                    <h4><a href="@Url.Action("Details", "Albums", new { Id = item.AlbumId })">@item.Album.Name</a></h4>
                                    <p>By @item.Album.Artist.Name</p>
                                </td>
                                <td class="cart_price">
                                    <p>@Helpers.GetCurrencyAndPrice(ViewBag.user, item.Album.Price)</p>
                                </td>
                                <td class="cart_quantity" data-cart-item-id="@item.Id">
                                    <div class="cart_quantity_button">
                                        <a class="cart_quantity_up" href="@Url.Action("UpdateQuantity", "Carts", new { cartItemId = item.Id, changeVector = 1 })"> + </a>
                                        <input class="cart_quantity_input" type="text" name="quantity" value="@item.Quantity" autocomplete="off" size="2">
                                        <a class="cart_quantity_down" href="@Url.Action("UpdateQuantity", "Carts", new { cartItemId = item.Id, changeVector = -1 })"> - </a>
                                    </div>
                                </td>
                                <td class="cart_total">
                                    <p class="cart_total_price">@Helpers.GetCurrencyAndPrice(ViewBag.user, item.Album.Price * item.Quantity)</p>
                                </td>
                                <td class="cart_delete">
                                    <a class="cart_quantity_delete" href="@Url.Action("Delete", "CartItems", new { id = item.Id })"><i class="fa fa-times"></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
        </div>
        <a class="btn btn-default check_out" href="@Url.Action("Create", "Orders")">Check Out</a>
    </div>
</section>